version: 2
updates:
    # Maintain dependencies for pom.xml
    - package-ecosystem: "maven"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "Maven pom.xml"
          include: "scope"
